name: python 3.6
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - matplotlib
  - sympy
  - slycot
  - lxml
  - pandas
  - xlrd
  - networkx
  - control
  - pip
  - pip:
    - svgpathtools
    - datetime
    - cobra
    - BondGraphTools==0.3.7

